### PR TITLE
Install kolibri-listcontent.py

### PR DESCRIPTION
**Pull request by starnight**
Install the script listing installed Kolibri content from Flathub flatpak package org.learningequality.Kolibri [1]. Then, it simplifies the flatpak packaging.

More detail discussion in the PR: Add org.endlessos.Key [2].

[1]: https://github.com/flathub/org.learningequality.Kolibri
[2]: https://github.com/flathub/flathub/pull/4481#discussion_r1316162995

### CODE REVIEW

**Comment by starnight** [comment]
Modified with linter check.

**Comment by starnight** [comment]
Add note:  This is part of [Publish the Endless Key app on Flathub](https://github.com/endlessm/endless-key-flatpak/issues/5)

**Comment by dbnicholson** [comment]
We should really propose this upstream as a management command (without the image builder format that I hope to move away from). But for now, this seems like a good idea.

**Review by dbnicholson — APPROVED** [review]
LGTM

**Comment by dbnicholson** [comment]
Actually, I started the CI again since the flatpak build was previously always building main. Since 925fbc8141c2f3c386e1feca653e7e8b4ed40a1c it will actually use the current checkout.

**Comment by starnight** [comment]
Verified with:
```
$ flatpak run --command=ls org.endlessos.Key.Devel /app/bin/kolibri-listcontent.py
/app/bin/kolibri-listcontent.py
```

**Pull request merged**
