### PR TITLE
Rebrand loading page for Endless Key

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
See first and second commit. The last commit is merely a reproduction of what translation changes would look like.

I'd like to get some feedback here first, before applying this change to all files.

A nice follow-up improvement where we inject a loading page might be feasible since https://github.com/learningequality/kolibri-app/pull/110 has been merged. I haven't looked at it yet.

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
This is how it looks right now:

[Gravação de tela de 2023-09-12 15-34-13.webm](https://github.com/endlessm/endless-key-flatpak/assets/3518204/d2b4ac08-c0b5-422c-aaba-10a8cf5932ed)

The error screen:

image

(I did not change error strings!)

**Comment by dylanmccall** [comment]
That seems fine for the moment, at least so we have a nice consistent-looking thing we can point to. I think it would be okay to drop the localized versions for now so we don't have to deal with those. We can add a follow-up task to switch to something like what [learningequality/kolibri-app](https://github.com/learningequality/kolibri-app) is doing now, or the same thing we're doing in [endlessm/kolibri-installer-android](https://github.com/endlessm/kolibri-installer-android) (but it would be nice if that was _also_ doing the shiny new thing from kolibri-app).

**Comment by dbnicholson** [comment]
I think this all goes away after #72 and any further improvements should be made in the `loading-screen` package in kolibri-explore-plugin.

**Comment by dylanmccall** [comment]
Yep, we can close this. With that said, I kind of want to get the Explore plugin to do a normal template override for the loading screen, and this branch could be a useful reference for that.

**Pull request closed without merging**
