### PR TITLE
Bump GNOME runtime to 45

### PR DESCRIPTION
**Pull request by starnight**
Bump GNOME runtime to 45. Besides, the Python is version 3.11 in the runtime.

This may help #55

### CODE REVIEW

**Comment by dbnicholson** [comment]
I don't think this will help #55 as GNOME Software runs on the host.

One thing I am worried about is the update to python 3.11. Kolibri bundles a lot of very old python packages in its quest to maintain python 2 compatibility. Recently I noted a warning running the Android build that something used by the ancient Django 1.11 release would be removed in 3.10. Apparently it's still working well enough, but I think it's more likely to become an actual problem.

**Comment by dbnicholson** [comment]
One thing to know is that the `--env=JSC_useDFGJIT=0` in the flatpak should be able to be dropped. My understanding with upstream is that the workaround in c4974d38e3a301f7ff8f82493dd233de7abf8499 should not be needed with the webkit in GNOME 45.

**Comment by starnight** [comment]
> One thing to know is that the `--env=JSC_useDFGJIT=0` in the flatpak should be able to be dropped. My understanding with upstream is that the workaround in [c4974d3](https://github.com/endlessm/endless-key-flatpak/commit/c4974d38e3a301f7ff8f82493dd233de7abf8499) should not be needed with the webkit in GNOME 45.

good catch!  Let me test without the environment variable.

**Comment by starnight** [comment]
Tested by removed `--env=JSC_useDFGJIT=0` with GNOME 45 runtime.  The app works.  So, add a commit to revert commit
https://github.com/endlessm/endless-key-flatpak/commit/c4974d38e3a301f7ff8f82493dd233de7abf8499 ("Disable JavaScript DFG JIT in WebKit").

**Review by dylanmccall — APPROVED** [review]

**Pull request merged**
